export const SOCIAL_FLOWERS_HOMEPAGE = {
  logoUrl: 'https://cdn.floristone.com/website-images/social-flowers-logo.svg',
  heroImage: 'https://cdn.socialflowers.com/fit-in/330x600/hero-image/sf-hero-transparent.png',
  heroImageAlt: 'Smiling woman holding red roses',
  heroSubheadline: 'A connection to remember: Fresh flower delivery using email, mobile or social media.',
  navigation: [
    { label: 'Shop', href: '/shop' },
    { label: 'How It Works', href: '/how-it-works' },
    { label: 'What People Say', href: '/reviews' },
    { label: 'FAQ', href: '/faq' },
    { label: 'About', href: '/about' },
  ],
  bestSellerImages: {
    preciousHeartBouquet: 'https://cdn.floristone.com/large/C15-4790_d1.jpg',
    sweetSurprisesBouquet: 'https://cdn.floristone.com/large/C12-4792_d1.jpg',
    stunningBeautyBouquet: 'https://cdn.floristone.com/large/C16-4839_d1.jpg',
    bloomingMasterpieceRoseBouquet: 'https://cdn.floristone.com/large/E4-4819_d1.jpg',
  },
  bestsellers: [
    {
      name: 'Precious Heart Bouquet',
      price: '115.00',
      href: '/item/C15-4790/precious-heart-bouquet/',
      image: 'https://cdn.floristone.com/large/C15-4790_d1.jpg',
    },
    {
      name: 'Sweet Surprises Bouquet',
      price: '105.00',
      href: '/item/C12-4792/sweet-surprises-bouquet/',
      image: 'https://cdn.floristone.com/large/C12-4792_d1.jpg',
    },
    {
      name: 'The Stunning Beauty Bouquet',
      price: '125.00',
      href: '/item/C16-4839/the-stunning-beauty-bouquet/',
      image: 'https://cdn.floristone.com/large/C16-4839_d1.jpg',
    },
    {
      name: 'The Blooming Masterpiece Rose Bouquet',
      price: '120.00',
      href: '/item/E4-4819/the-blooming-masterpiece-rose-bouquet/',
      image: 'https://cdn.floristone.com/large/E4-4819_d1.jpg',
    },
  ],
  flowerMe: {
    description: 'A new way to be celebrated, receive flowers, and feel adored. Watch the video below and learn more.',
    videoUrl: 'https://cdn.socialflowers.com/flowerme/Blooming_This_Fall_2025.mp4#t=0.001',
    thumbnailUrl: 'https://cdn.socialflowers.com/thumbnails/flowerme/Blooming_This_Fall_2025.mp4.0000024.jpg',
  },
  customBouquets: {
    heading: 'Send Flowers Easily With Custom Bouquets',
    recipientsChoiceImage: 'https://cdn.floristone.com/large/recipients-choice-thumb.jpg',
    sendersChoiceImage: 'https://cdn.floristone.com/large/senders-choice.jpg',
  },
  benefits: {
    everyone: 'https://cdn.socialflowers.com/benefits/for_everyone.svg',
    sender: 'https://cdn.socialflowers.com/benefits/for_senders.svg',
    recipient: 'https://cdn.socialflowers.com/benefits/for_recipients.svg',
  },
  footer: {
    socialLinks: [
      { platform: 'twitter', href: 'https://twitter.com/Social_Flowers' },
      { platform: 'instagram', href: 'https://www.instagram.com/social.flowers/' },
      { platform: 'tiktok', href: 'https://www.tiktok.com/@social.flowers' },
      { platform: 'facebook', href: 'https://www.facebook.com/socialflowers1' },
      { platform: 'linkedin', href: 'https://www.linkedin.com/company/social-flowers' },
    ],
    shop: [
      { label: 'Best Sellers', href: '/best-sellers' },
      { label: 'Love & Romance', href: '/romance-flowers' },
      { label: 'Roses', href: '/roses' },
      { label: 'High End', href: '/high-end-flowers' },
      { label: 'Just Because', href: '/everyday-flowers' },
      { label: 'Get Well', href: '/get-well-flowers' },
      { label: 'Birthday', href: '/birthday-flowers' },
      { label: 'New Baby', href: '/new-baby-flowers' },
      { label: 'Thank You', href: '/thank-you-flowers' },
      { label: "I'm Sorry", href: '/sorry-flowers' },
      { label: 'Funeral & Sympathy', href: '/sympathy-flowers' },
      { label: 'Plants', href: '/plants' },
    ],
    company: [
      { label: 'Contact', href: '/contact' },
      { label: 'About', href: '/about' },
      { label: 'How It Works', href: '/how-it-works' },
      { label: 'FAQ', href: '/faq' },
      { label: 'FlowerMe Society', href: 'https://flowerme.socialflowers.com/' },
      { label: 'Customer Service Policy', href: '/customer-service' },
      { label: 'Local Florist Delivery', href: '/local-florist-delivery' },
      { label: 'Privacy', href: '/privacy' },
      { label: 'Blog', href: '/blog' },
    ],
    uses: [
      { label: 'Dating', href: '/date/' },
      { label: 'Social Media', href: '/social-media/' },
      { label: 'Facebook', href: '/social-media/facebook' },
      { label: 'Instagram', href: '/social-media/instagram' },
      { label: 'OnlyFans', href: '/social-media/onlyfans' },
      { label: 'Wishlists', href: '/wishlist/' },
      { label: 'In the Workplace', href: '/work/' },
      { label: 'To a Hospital', href: '/hospital/' },
      { label: 'To a Funeral Home', href: '/funeral-home/' },
      { label: 'To a Hotel', href: '/hotel/' },
      { label: 'Saying Sorry', href: '/sorry/' },
      { label: 'To a Companion', href: '/companion/' },
      { label: 'From Overseas', href: '/overseas/' },
      { label: 'Pay With Crypto', href: '/crypto/' },
      { label: 'Anonymous Flower Delivery', href: '/anonymously/' },
    ],
  },
  headings: {
    hero: 'Send Flowers Without Knowing Their Address',
    bestSellers: 'Our Bestsellers',
    flowerMe: 'The FlowerMe Society is Here!',
    customBouquets: 'Send Flowers Easily With Custom Bouquets',
    howItWorks: 'How Social Flowers Works',
    benefits: 'The Benefits of the Social Flowers Solution',
    bestsellersCta: 'More Items',
    flowerMeLearnMore: 'learn more.',
  },
} as const