const CREDIT_REASONS = {
  PHOTO_SHARED: 'photo_shared',
  VIDEO_SHARED: 'video_shared',
  SOCIAL_SHARE: 'social_share',
  UGC_POST: 'ugc_post',
  CHECKOUT_CREDIT_APPLIED: 'checkout_credit_applied',
  ADMIN_ADJUSTMENT: 'admin_adjustment',
};

const CREDIT_REASON_ENUM = [
  CREDIT_REASONS.PHOTO_SHARED,
  CREDIT_REASONS.VIDEO_SHARED,
  CREDIT_REASONS.SOCIAL_SHARE,
  CREDIT_REASONS.UGC_POST,
  CREDIT_REASONS.CHECKOUT_CREDIT_APPLIED,
  CREDIT_REASONS.ADMIN_ADJUSTMENT,
];

const CREDIT_EARN_REWARD_TABLE = {
  [CREDIT_REASONS.PHOTO_SHARED]: 5,
  [CREDIT_REASONS.VIDEO_SHARED]: 10,
  [CREDIT_REASONS.SOCIAL_SHARE]: 3,
  [CREDIT_REASONS.UGC_POST]: 7,
};

const CREDIT_EARN_REASONS = Object.keys(CREDIT_EARN_REWARD_TABLE);

module.exports = {
  CREDIT_REASONS,
  CREDIT_REASON_ENUM,
  CREDIT_EARN_REWARD_TABLE,
  CREDIT_EARN_REASONS,
};
